const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="keithkuboka@gmail.com"
global.location="Nairobi, Kenya."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "postgres://koyeb-adm:yMm1d7QIkhgr@ep-gentle-silence-a2enaqk4.eu-central-1.pg.koyeb.app/koyebdb"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/Keith-Rich";
global.gurl  =process.env.GURL  || "https://chat.whatsapp.com/EoJFKdX37v26ZA9g6p8SAN";
global.website=process.env.GURL || "https://chat.whatsapp.com/EoJFKdX37v26ZA9g6p8SAN" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴀʀᴛᴇᴍɪꜱ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "254784900006";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '1'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 1
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_05_36_06_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAyMTcsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTMsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjUyLFxuICAgICAgICAyNTMsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTk3LFxuICAgICAgICA0MCxcbiAgICAgICAgOTksXG4gICAgICAgIDIxLFxuICAgICAgICAyMDQsXG4gICAgICAgIDg3LFxuICAgICAgICAxOTIsXG4gICAgICAgIDEwMyxcbiAgICAgICAgNDAsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTM4LFxuICAgICAgICAxNzIsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMyxcbiAgICAgICAgMjIzLFxuICAgICAgICAxMTYsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMTksXG4gICAgICAgIDE3MixcbiAgICAgICAgMSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNzgsXG4gICAgICAgIDEwMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNDMsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTE5LFxuICAgICAgICA4MyxcbiAgICAgICAgODksXG4gICAgICAgIDQ3LFxuICAgICAgICAyMzEsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjI0LFxuICAgICAgICA2NyxcbiAgICAgICAgODksXG4gICAgICAgIDE2NixcbiAgICAgICAgMjI3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDg1LFxuICAgICAgICA2OCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNzIsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMTM1LFxuICAgICAgICA2LFxuICAgICAgICA3MixcbiAgICAgICAgNzcsXG4gICAgICAgIDE2MyxcbiAgICAgICAgNTQsXG4gICAgICAgIDY3LFxuICAgICAgICAyNSxcbiAgICAgICAgMTkwLFxuICAgICAgICAxNjMsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMzEsXG4gICAgICAgIDg3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzMixcbiAgICAgICAgMTAzLFxuICAgICAgICAyMTksXG4gICAgICAgIDgxLFxuICAgICAgICAzOSxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNTYsXG4gICAgICAgIDU1LFxuICAgICAgICAxMSxcbiAgICAgICAgMzEsXG4gICAgICAgIDkwLFxuICAgICAgICAyMDksXG4gICAgICAgIDE2MyxcbiAgICAgICAgNjIsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTUyLFxuICAgICAgICAzOSxcbiAgICAgICAgOTQsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxNixcbiAgICAgICAgMjI2LFxuICAgICAgICAxNixcbiAgICAgICAgMTE4LFxuICAgICAgICAyMzIsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTExLFxuICAgICAgICAyNDksXG4gICAgICAgIDEwMVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDEsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTI2LFxuICAgICAgICA3OCxcbiAgICAgICAgMTE2LFxuICAgICAgICA3OCxcbiAgICAgICAgNTQsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTQwLFxuICAgICAgICAyNTEsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjM0LFxuICAgICAgICA4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDgxLFxuICAgICAgICA5MixcbiAgICAgICAgMTYzLFxuICAgICAgICA0OSxcbiAgICAgICAgMTA3LFxuICAgICAgICA3OSxcbiAgICAgICAgMTM1LFxuICAgICAgICAyMDYsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTI2LFxuICAgICAgICAyMzcsXG4gICAgICAgIDk4LFxuICAgICAgICAyLFxuICAgICAgICAxNDksXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMCxcbiAgICAgICAgOThcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MCxcbiAgICAgICAgOTcsXG4gICAgICAgIDQ0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDE0MixcbiAgICAgICAgNTIsXG4gICAgICAgIDI0OCxcbiAgICAgICAgOTQsXG4gICAgICAgIDc5LFxuICAgICAgICA0NyxcbiAgICAgICAgMTYsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTUzLFxuICAgICAgICAxNTUsXG4gICAgICAgIDExMCxcbiAgICAgICAgNjEsXG4gICAgICAgIDIwOCxcbiAgICAgICAgOTAsXG4gICAgICAgIDE5NSxcbiAgICAgICAgNzQsXG4gICAgICAgIDYxLFxuICAgICAgICAyMzQsXG4gICAgICAgIDQzLFxuICAgICAgICAyMDEsXG4gICAgICAgIDU4LFxuICAgICAgICAxOTMsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNTcsXG4gICAgICAgIDYxLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE0NSxcbiAgICAgICAgOTNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDcsXG4gICAgICAgIDEyLFxuICAgICAgICAxMTMsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjU1LFxuICAgICAgICAyMDAsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTgwLFxuICAgICAgICAyNixcbiAgICAgICAgOTksXG4gICAgICAgIDkyLFxuICAgICAgICAxMzYsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTAzLFxuICAgICAgICA2MyxcbiAgICAgICAgNTgsXG4gICAgICAgIDgxLFxuICAgICAgICA2OSxcbiAgICAgICAgMjIzLFxuICAgICAgICAxMjQsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTA3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDUyLFxuICAgICAgICA5LFxuICAgICAgICA3MSxcbiAgICAgICAgODIsXG4gICAgICAgIDIzNSxcbiAgICAgICAgNTAsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjEzLFxuICAgICAgICAxMjJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxNzMsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMTc3LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDY2XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE5MCxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDY3XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjUsXG4gICAgICAgIDUzLFxuICAgICAgICAyMjMsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTI3LFxuICAgICAgICA0MCxcbiAgICAgICAgNTAsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNzksXG4gICAgICAgIDE0NixcbiAgICAgICAgMjEzLFxuICAgICAgICAxNDYsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMjA1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE5NixcbiAgICAgICAgOTEsXG4gICAgICAgIDUwLFxuICAgICAgICA0LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMTU4LFxuICAgICAgICA3MixcbiAgICAgICAgMTAwLFxuICAgICAgICAxNjAsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxMTIsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjE3LFxuICAgICAgICAzNyxcbiAgICAgICAgMTIwLFxuICAgICAgICAxNzMsXG4gICAgICAgIDgwLFxuICAgICAgICAyMTEsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTE0LFxuICAgICAgICA3MixcbiAgICAgICAgMzYsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTQzLFxuICAgICAgICAxNSxcbiAgICAgICAgNTQsXG4gICAgICAgIDI5LFxuICAgICAgICA5MSxcbiAgICAgICAgMjA1LFxuICAgICAgICAyNSxcbiAgICAgICAgOTksXG4gICAgICAgIDgyLFxuICAgICAgICAxOCxcbiAgICAgICAgOTAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMzgsXG4gICAgICAgIDI5LFxuICAgICAgICA3MCxcbiAgICAgICAgMjAyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxMzlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE4NCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIwMGhIdm16SlpkQXc3R21PODhMVVZranlGS2pJaVNMRll1OHY2QXpJN2FZPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1NDExMzMyODkwN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiRTNGODZGOEY3REQ0QjJDMzAyOTAzNzUzODk3Nzg2QkJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE3NTY1ODE1XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0MTEzMzI4OTA3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI1QTU0NDVGNEIyQzIyOTQyRDMxNTYxODlFNDlGNkY3OVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTc1NjU4MTZcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiQUx4NGdvN09TWHFnX3JzbnB4X2pmQVwiLFxuICBcInBob25lSWRcIjogXCIwNGIxZDY2NS1jNmE5LTRlYWEtYmJkZi04ZGZmYzMyMGU2MjBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNixcbiAgICAgIDIzNCxcbiAgICAgIDEzNSxcbiAgICAgIDY1LFxuICAgICAgMzYsXG4gICAgICAxNTcsXG4gICAgICAyMTAsXG4gICAgICAxMzQsXG4gICAgICAyMDAsXG4gICAgICA1NyxcbiAgICAgIDE2NixcbiAgICAgIDIzNixcbiAgICAgIDE1LFxuICAgICAgMTM4LFxuICAgICAgMjUzLFxuICAgICAgMTEzLFxuICAgICAgMTcyLFxuICAgICAgOTAsXG4gICAgICAxNCxcbiAgICAgIDI0MVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjQzLFxuICAgICAgNDUsXG4gICAgICA3OSxcbiAgICAgIDExLFxuICAgICAgMTU3LFxuICAgICAgMTE1LFxuICAgICAgMjMyLFxuICAgICAgNjQsXG4gICAgICAyMDAsXG4gICAgICAyMDEsXG4gICAgICA0MixcbiAgICAgIDIyMCxcbiAgICAgIDEzNSxcbiAgICAgIDE3NixcbiAgICAgIDE2LFxuICAgICAgMTAzLFxuICAgICAgNyxcbiAgICAgIDQ3LFxuICAgICAgMzcsXG4gICAgICA0MFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0ppaTI3d0dFTzd5LzdJR0dBTWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiWU5tM0QyOEo0NHhLWElsWVNyeFlSWDZQSkh2SG9hTkxHK0pJblY4d2ozUT1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJGTWtXdHpaQzEwNFFrTkVBS3FKTys5K01DMEUvbHJXNG9Fa0tlT0ROdVFnVUROaUowZnZTMFdXZzJQSDd0L2h4NGZMc0RYVTltb0F1ODh2TGMzUDVDQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJ6UzBuWTl0Rzg0NHNmMDNLRGRGWVZydHNZcU02RURoV0tOTWJaZk9YYzRjQmtTQWduQ1VGR3dXTXAzY1ErZWZMNHdBYVNGZEJYMXJncDNrcGlUVWlpQT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1NDExMzMyODkwNzoyNkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMzgxOTk3NTc5MjIzNjI6MjZAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiw5fNnMOXXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyNTQxMTMzMjg5MDc6MjZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICA5LFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxMTZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcxNzU2NTgxMCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUwyL1wiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTDIrLmpzb24iOiAie1wia2V5RGF0YVwiOlwicEtaOVJ0cmRxc2VzWTZjSnVHV0VCaitYQU1vTlBrcm9MY2lETEJxUDFlbz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNzM3OTM3MTc1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MDgyMzQ0NzExODNcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMMl9fLmpzb24iOiAie1wia2V5RGF0YVwiOlwidWhSZkpSNXJQZHltMzJIUnFBS0cyTmdsMjlpamxwZmJmVW54TFNZRFV1ND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNzM3OTM3MTc1LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxLDJdfSxcInRpbWVzdGFtcFwiOlwiMTcxMDg1NjYxMTU0OVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUwzQS5qc29uIjogIntcImtleURhdGFcIjpcIk1RY2RyWHBiVTNFKzQ1UG5keWhOWUdCUUlZakJwVmkvdkZvdll4ZldZYzg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTczNzkzNzE3NSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSwyXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTM5MDAxMTkwMDRcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMM0IuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI0ZWQ4d3dwQkNReVNDdkZMRmNzdGJlMnVhLzBnZ1dCTGVUa3dVY05rK3FBPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE3Mzc5MzcxNzUsXCJjdXJyZW50SW5kZXhcIjoyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsMl19LFwidGltZXN0YW1wXCI6XCIxNzE2NTczMzQzMjQ0XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTDNDLmpzb24iOiAie1wia2V5RGF0YVwiOlwid3ZIZzBTS3hkTEtlTmhYemowMGI3TEppUGM5Q2NhTGIwR0dsNU9aWURLMD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNzM3OTM3MTc1LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzE3NDg2NTEwNTkwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTDNELmpzb24iOiAie1wia2V5RGF0YVwiOlwianZGanhqNTd6MmRCeVNxQ05ZTzNiYmM0S29vdzFmU2tEM0JNVnhCb2J4cz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNzM3OTM3MTc2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTc1NjMxMjI0NDFcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.7",
  caption : global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴀʀᴛᴇᴍɪꜱ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "ᴍʀ.ꜱᴜᴘᴇʀᴍᴀɴ",
  packname: process.env.PACK_NAME || "ᴀʀᴛᴇᴍɪꜱ' ᴛᴇᴄʜ ×͜×",
  botname : process.env.BOT_NAME  || "ᴀʀᴛᴇᴍɪꜱ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "ᴍʀ.ꜱᴜᴘᴇʀᴍᴀɴ",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "true",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "xyiGHHQdzZ9pSvEWRvNh8v1Y",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "41dbeca0157ebaf4945e4576f6045cb3";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
